config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :parks, except: [:index] do
    resource :favorite, only: [:create, :destroy]
  end

  resources :prefectures, only: [] do
    resources :parks, only: [:index]
  end

  resources :parks, only: [:new, :create, :index, :show, :destroy] do
    resources :park_comments, only: [:create]
  end

  root to: 'homes#top'
  get '/about', to: 'homes#about', as: :about

   get 'users/:id' => 'users#show', as: 'name'

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :park

  validates :user_id, uniqueness: {scope: :park_id}
end

app/models/park.rb
class Park < ApplicationRecord
  belongs_to :prefecture
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :park_comments, dependent: :destroy
  has_one_attached :image

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :image, presence: true



end

app/models/park_comment.rb
class ParkComment < ApplicationRecord
  belongs_to :user
  belongs_to :park
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  belongs_to :region
  has_many :parks, dependent: :destroy

  validates :name, uniqueness: true
  validates :slug, uniqueness: true
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :prefectures, dependent: :destroy

  validates :name, uniqueness: true
  validates :slug, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :parks
   has_many :park_comments, dependent: :destroy

  has_one_attached :image

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    park = Park.find(params[:park_id])
    favorite = current_user.favorites.new(park_id: park.id)
    favorite.save
    redirect_to park_path(park)
  end

  def destroy
    park = Park.find(params[:park_id])
    favorite = current_user.favorites.find_by(park_id: park.id)
    favorite.destroy
    redirect_to park_path(park)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @regions = Region.all
  end

  def about
    @title = "About"
  end

end

app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
  def index
  end

  def show
    @park = Park.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/park_comments_controller.rb
class ParkCommentsController < ApplicationController
  def create
    park = Park.find(params[:park_id])
    comment = current_user.park_comments.new(park_comment_params)
    comment.park_id = park.id
    comment.save
    redirect_to park_path(park)
  end

  private

  def park_comment_params
    params.require(:park_comment).permit(:comment)
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    @park.user_id = current_user.id
    if @park.save
      redirect_to @park
    else
      render :new
    end

  end


  def index
    @prefecture = Prefecture.find(params[:prefecture_id])
    @parks = @prefecture.parks
  end

  def show
    @park = Park.find(params[:id])
    @park_comment = ParkComment.new
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    park = Park.find(params[:id])
    park.update(park_params)
    redirect_to park_path(park.id)
  end

  def bookmarks
    @bookmarks_boards = current_user.bookmark_boards.includes(:user).order(created_at: :desc)#後で定義する
  end

  def destroy
    park = Park.find(params[:id])
    park.destroy
    redirect_to user_path(current_user)
  end


  private

  def park_params
    params.require(:park).permit(:name, :description, :address, :prefecture_id, :image)
  end

  def ensure_guest_user

    if current_user.email == "guest@example.com"
      redirect_to root_path
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "guestuserでログインしました。"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

    @users = User.all
  end

  def show
  @user = User.find(params[:id])
    if @user.nil?
      flash[:error] = "ユーザーが見つかりません"
      redirect_to users_path
    end
  end

  def edit
      user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end

    @user = User.find(params[:id])
  end

  def update
      user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end

    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to new_user_registration_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/park_comments_helper.rb
module ParkCommentsHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1></h1>
<h3>ここは公園についていいと思ったり、これ持っていけばよかった！など、好きに書き込んでレビューして、自由な口コミサイトです。</br>
公園に関する情報や、どんな公園に行きたいか予定を立てる際にも、是非活用してください！</h3>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 m-4">
      <% if user_signed_in? %>
        <button type="button" class="btn btn-light">
          <%= link_to "new park", new_park_path %>
        </button>
      <% end %>
    </div>
  </div>
  <div class="row">
    <% @regions.each do |region| %>
      <div class="col-sm-12 mb-4">
        <p class="mb-1"><%= region.name %></p>
        <% region.prefectures.each do |prefecture| %>
          <%= link_to prefecture.name, prefecture_parks_path(prefecture), class: "mr-2" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

      <!-- <button type="button" class="btn btn-primary">Primary</button>
      <button type="button" class="btn btn-secondary">Secondary</button>
      <button type="button" class="btn btn-success">Success</button>
      <button type="button" class="btn btn-danger">Danger</button>
      <button type="button" class="btn btn-warning">Warning</button>
      <button type="button" class="btn btn-info">Info</button>
      <button type="button" class="btn btn-light">Light</button>
      <button type="button" class="btn btn-dark">Dark</button>
      <button type="button" class="btn btn-link">Link</button> -->

app/views/parks/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @park do |f| %>

　<h4>画像</h4>
  <%= f.file_field :image %>

  <h4>公園名</h4>
  <%= f.text_field :name%>

  <h4>説明文</h4>
  <%= f.text_area :description %>

  <%= f.submit '保存' %>

<% end %>
<%= link_to '戻る', park_path %>

app/views/parks/index.html.erb
<h2><%= @prefecture.name %>の公園</h2>
<div class= "row" >
  <div class="col-12">
    <div class="card-columns">
      <% @parks.each do |park| %>
        <div class="card">
            <% if park.image.attached?%>
              <%= image_tag park.image, class: "w-100", height: "350px" %>
            <% else %>
              <%= image_tag "no_image.jpg", class: "w-100", height: "350px" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title">
                <p>公園名</p>
                <span>
                  <%= link_to park.name, park%></h5>
                </span>
                <p><%= park.user.name %></p>
                <p><%= link_to "#{park.park_comments.count} コメント", park_path(park.id) %></p>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<%= link_to '戻る', root_path %>

app/views/parks/new.html.erb
<h3>どんな公園?</h3>
<% if @park.errors.any? %>
  <%= @park.errors.count %>件のエラーが発生しました
  <ul>
    <% @park.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @park do |f| %>
  <h4>公園名</h4>
  <%= f.text_field :name %>

  <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name) %>

  <h4>説明文</h4>
  <%= f.text_area :description %>

  <h4>場所</h4>
  <%= f.text_area :address %>

  <h4>画像</h4>
  <%= f.file_field :image, accept: "image/*" %>


  <%= f.submit '投稿' %>
<% end %>

app/views/parks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 m-4">
      <p>画像</p>
      <p><%= image_tag @park.image, size: "200x200" %></p>
      <p>公園名：<%= @park.name%></p>
      <p>都道府県名：<%= @park.prefecture.name %></p>
      <p>住所：<%= @park.address %></p>
      <p>紹介：<%= @park.description%></p>
      <p>ユーザーネーム：<%= @park.user.name %></p>

    </div>
  </div>
</div>

    <% if @park.favorited_by?(current_user) %>
    <p>
      <%= link_to park_favorite_path(@park), method: :delete do %>
        ♥<%= @park.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to park_favorite_path(@park), method: :post do %>
        ♡<%= @park.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
</div>
<% if @park.user_id == current_user.id %>
  <%= link_to '編集', edit_park_path(@park) %>
<% end %>

<%= link_to '戻る', prefecture_parks_path(@park.prefecture.id) %></br>

<% if @park.user_id == current_user.id %>
  <%= link_to '削除', park_path(@park), method: :delete, "data-confirm" => "本当に削除しますか？"  %>
<% end %>

<div>
  <p>コメント件数：<%= @park.park_comments.count %></p>
  <% @park.park_comments.each do |park_comment| %>
    <div>
      <%= park_comment.user.name %>
      <%= park_comment.created_at.strftime('%Y/%m/%d') %><%= park_comment.comment %>
    </div>
  <% end %>
</div>
<div>
  <%= form_with model: [@park, @park_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>編集画面</h1>

<%= form_with model: @user do |f| %>

  <h4>画像</h4>
  <%= f.file_field :image %>

  <h4>name</h4>
  <%= f.text_area :name %>

  <% if @user.email != "guest@example.com" %>
    <h4>email</h4>
    <%= f.text_field :email %>
  <% end %>

  <%= f.submit '保存' %>

<% end %>
<%= link_to '戻る', user_path %>

app/views/users/index.html.erb
<h1>全ユーザー</h1>
<div class= "row" >
  <div class="col-12">
    <div class="card-columns">
      <% @users.each do |user| %>
        <div class="card">
            <% if user.image.attached?%>
              <%= image_tag user.image, class: "w-100", height: "350px" %>
            <% else %>
              <%= image_tag "no_image.jpg", class: "w-100", height: "350px" %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title">
                <p>ユーザー名</p>
                <span>
                  <%= link_to user.name, user_path(user.id) %></h5>
                </span>
            </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= link_to '戻る', root_path %>

app/views/users/show.html.erb
<h1>ユーザー詳細</h1>
<p id="notice"></p>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <p>画像: <%= image_tag (@user.image.present? ? @user.image : "no_image.jpg"), size: "200x200" %></p></br>
      <p>ユーザー名: <%= @user.name %></p>
      <p>メールアドレス: <%= @user.email %></p>
      <p>コメント数: <%= @user.park_comments.count %> </p>
    </div>
  </div>
</div>
<% if @user == current_user %>
  <%= link_to '編集', edit_user_path(@user) %>
<% end %>

<%= link_to '戻る', users_path(@user) %></br>

<% if @user == current_user %>
  <%= link_to '削除', user_path(@user), method: :delete, "data-confirm" => "本当に削除しますか？"  %>
<% end %>