config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :parks, except: [:index] do
    resource :favorite, only: [:create, :destroy]
  end

  resources :prefectures, only: [] do
    resources :parks, only: [:index]
  end

  resources :parks, only: [:new, :create, :index, :show, :destroy] do
    resources :park_comments, only: [:create]
  end

  root to: 'homes#top'
  get '/about', to: 'homes#about', as: :about

   get 'users/:id' => 'users#show', as: 'name'

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :park

  validates :user_id, uniqueness: {scope: :park_id}
end

app/models/park.rb
class Park < ApplicationRecord
  belongs_to :prefecture
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :park_comments, dependent: :destroy
  has_one_attached :image

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :name, presence: true
  validates :address, presence: true
  validates :description, presence: true
  validates :image, presence: true



end

app/models/park_comment.rb
class ParkComment < ApplicationRecord
  belongs_to :user
  belongs_to :park
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  belongs_to :region
  has_many :parks, dependent: :destroy

  validates :name, uniqueness: true
  validates :slug, uniqueness: true
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :prefectures, dependent: :destroy

  validates :name, uniqueness: true
  validates :slug, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :parks
   has_many :park_comments, dependent: :destroy

  has_one_attached :image

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    about_path
  end

  def after_sign_out_path_for(resource)
    about_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    park = Park.find(params[:park_id])
    favorite = current_user.favorites.new(park_id: park.id)
    favorite.save
    redirect_to park_path(park)
  end

  def destroy
    park = Park.find(params[:park_id])
    favorite = current_user.favorites.find_by(park_id: park.id)
    favorite.destroy
    redirect_to park_path(park)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @regions = Region.all
  end

  def about
    @title = "About"
  end

end

app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
  def index
  end

  def show
    @park = Park.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :authenticate_user!, only: [:new]

  def new
    @park = Park.new
  end

  def create
    @park = Park.new(park_params)
    @park.user_id = current_user.id
    if @park.save
      redirect_to @park
    else
      render :new
    end

  end


  def index
    @prefecture = Prefecture.find(params[:prefecture_id])
    @parks = @prefecture.parks
  end

  def show
    @park = Park.find(params[:id])
    @park_comment = ParkComment.new
  end

  def edit
    @park = Park.find(params[:id])
  end

  def update
    park = Park.find(params[:id])
    park.update(park_params)
    redirect_to park_path(park.id)
  end

  def bookmarks
    @bookmarks_boards = current_user.bookmark_boards.includes(:user).order(created_at: :desc)#後で定義する
  end

  def destroy
    park = Park.find(params[:id])
    park.destroy
    redirect_to user_path(current_user)
  end


  private

  def park_params
    params.require(:park).permit(:name, :description, :address, :prefecture_id, :image)
  end

  def ensure_guest_user

    if current_user.email == "guest@example.com"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

    @users = User.all
  end

  def show
  @user = User.find(params[:id])
    if @user.nil?
      flash[:error] = "ユーザーが見つかりません"
      redirect_to users_path
    end
  end

  def edit
      user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end

    @user = User.find(params[:id])
  end

  def update
      user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to users_path
    end

    user = User.find(params[:id])
    user.update(user_params)
    redirect_to user_path(user.id)
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to new_user_registration_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/park_comments_helper.rb
module ParkCommentsHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Go Park</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/0bcafbffc0.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand navbar-dark bg-dark">
        <div class="container">
            <%= link_to new_park_path, class: "navbar-brand" do %>
              <h3>Go Park</h3>
            <% end %>
          <div class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to root_path, class: "nav-link text-light" do %>
                    <i class="fa-regular fa-image"></i> Top
                  <% end %>
                </li>
                <li>
                  <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                    <i class="fa-solid fa-user"></i> My page
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-users"></i> Users
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "nav-link text-light" do %>
                    <i class="fa-regular fa-address-card"></i> about
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-right-from-bracket"></i> Log out
                  <% end %>
                </li>
              <% else %>

                <li>
                  <%= link_to users_guest_sign_in_path, class: "nav-link text-light", method: :post do %>
                    <i class="fa-solid fa-g"></i> ゲストログイン
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                    <i class="fa-solid fa-right-to-bracket"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container">
        <div class="col-sm-12 mb-1">
          <%= yield %>
        </div>
      </div>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>